swagger: '2.0'
info:
  title: Shifter API
  description: Shifter API allows you to operate all Shifter resources, which are projects, archives, App, Generator.
  version: "0.1.0"
host: hz0wknz3a2.execute-api.us-east-1.amazonaws.com
schemes:
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: You can authorize Shifter using the accesstoken.
basePath: /production
produces:
  - application/json
paths:
  /login:
    post:
      description: You can get accesstoken to access shifter resources.
      tags:
        - login
      parameters:
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoginPostRequest'
      responses:
        200:
          description: Login success
          schema:
            "$ref": "#/definitions/LoginPostResponse"
  /projects:
    get:
      description: You can get the infomation of your projects
      tags:
        - projects
      security:
        - Bearer: []
      responses:
        200:
          description: the info of your projects
          schema:
            type: array
            items:
              "$ref": "#/definitions/ProjectsGetResponse"
    post:
      description: Create new project
      tags:
        - projects
      security:
        - Bearer: []
      parameters:
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/ProjectsPostRequest'
        - name: archive_id
          in: query
          required: true
          description: Specify an archive to create a project
          type: string
      responses:
        200:
          description: Success
  /projects/{site_id}:
    delete:
      description: Delete your project
      tags:
        - projects
      security:
        - Bearer: []
      parameters:
        - name: site_id
          in: path
          required: true
          description: project ID
          type: string
      responses:
        200:
          description: Success
  /containers/{site_id}:
    get:
      description: You can the status of App
      security:
        - Bearer: []
      tags:
        - containers
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
        - name: notification_id
          in: query
          required: true
          description: ID required to acquire App state
          type: string
      responses:
        200:
          description: the status of App
          schema:
            type: string
    post:
      description: Import archive to App
      security:
        - Bearer: []
      tags:
        - containers
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/ContainersPostRequest'
      responses:
        200:
          description: 成功
    put:
      description: Start App
      security:
        - Bearer: []
      tags:
        - containers
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
    delete:
      description: Stop App
      security:
        - Bearer: []
      tags:
        - containers
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
  /staticsites/{site_id}:
    get:
      description: You can get the process of generating
      security:
        - Bearer: []
      tags:
        - staticsites
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: the process of generating
          schema:
            $ref: '#/definitions/StaticsitesGetResponse'
    post:
      description: Start to generate the plblished site.
      security:
        - Bearer: []
      tags:
        - staticsites
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
    delete:
      description: Delete the published site
      security:
        - Bearer: []
      tags:
        - staticsites
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
  /status:
    get:
      description: You can get the status of your account and shifter
      security:
        - Bearer: []
      tags:
        - status
      responses:
        200:
          description: the process of generating
          schema:
            $ref: '#/definitions/StatusGetResponse'
  /generatehistory/{site_id}:
    get:
      description: You can get the history of generating in the project
      security:
        - Bearer: []
      tags:
        - generatehistory
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: the history of generating
          schema:
            $ref: '#/definitions/GeneratehistoryGetResponse'
  /support:
    post:
      description: You can get the SSO endpoint for Zendesk.
      security:
        - Bearer: []
      tags:
        - support
      responses:
        200:
          description: Get SSO Endpoint
          schema:
            $ref: '#/definitions/SupportPostResponse'
  /transactions/{site_id}:
    get:
      description: You can get the transfer amount for Shifter CDN
      security:
        - Bearer: []
      tags:
        - transactions
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
        - name: start_month
          in: query
          type: integer
          description: 'Start month of the period you want to acquire the transfer amount ex: 201605'
        - name: range
          in: query
          type: integer
          description: 'Period for acquiring it (the month) ex: 12'
      responses:
        200:
          description: Get the transfer data
  /accounts/{username}:
    delete:
      description: You can delete your account
      security:
        - Bearer: []
      tags:
        - accounts
      parameters:
        - name: username
          in: path
          required: true
          type: string
      responses:
        200:
          description: Get the info
          schema:
            $ref: '#/definitions/AccountsDeleteResponse'
definitions:
  LoginPostRequest:
    properties:
      username:
        type: string
      password:
        type: string
  LoginPostResponse:
    properties:
      AccessToken:
        type: string
  ProjectsGetResponse:
    properties:
      site_id:
        type: string
        description: project ID
      site_name:
        type: string
        description: project name
      site_owner:
        type: string
        description: the owner of project
      update_time:
        type: string
        description: published date by Generator
      docker_url:
        type: string
        description: App Url
  ProjectsPostRequest:
    properties:
      projectName:
        type: string
        description: project name
      phpVersion:
        type: string
        description: php version is used in the project
  ContainersPostRequest:
    properties:
      archive_id:
        type: string
  StaticsitesGetResponse:
    properties:
      percent:
        type: integer
        description: Progress rate of genetating
      step:
        type: string
        description: Progress step  of genetating
      update_time:
        type: string
      owner:
        type: string
      message:
        type: string
      disk_usage:
        type: string
  StatusGetResponse:
    properties:
      maintenance:
        properties:
          message:
            type: string
          target:
            type: array
            items:
              type: string
          status:
            type: string
      user:
        properties:
          creditCardStatus:
            type: string
          upperLimitProjects:
            type: integer
          upperLimitArchives:
            type: integer
          upperLimitDomains:
            type: integer
  GeneratehistoryGetResponse:
    properties:
      Items:
        type: array
        items:
          properties:
            create_time:
              type: string
            update_time:
              type: string
            progress:
              type: string
            message:
              type: string
  SupportPostResponse:
    properties:
      ssoEndpoint:
        type: string
  AccountsDeleteResponse:
    properties:
      statusCode:
        type: integer
      message:
        type: string
