swagger: '2.0'
info:
  title: Shifter API
  description: Shifter API allows you to operate all Shifter resources, which are projects, archives, App, Generator.
  version: "1.0.0"
host: hz0wknz3a2.execute-api.us-east-1.amazonaws.com
schemes:
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: You can authorize Shifter using the accesstoken.
basePath: /production
produces:
  - application/json
paths:
  /projects:
    get:
      description: You can get the infomation of your projects
      security:
        - Bearer: []
      responses:
        200:
          description: the info of your projects
          schema:
            type: array
            items:
              "$ref": "#/definitions/ProjectsGetResponse"
    post:
      description: Create new project
      security:
        - Bearer: []
      parameters:
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/ProjectsPostRequest'
      responses:
        200:
          description: Success
definitions:
  ProjectsGetResponse:
    properties:
      site_id:
        type: string
        description: project ID
      site_name:
        type: string
        description: project name
      site_owner:
        type: string
        description: the owner of project
      update_time:
        type: string
        description: published date by Generator
      docker_url:
        type: string
        description: App Url
  ProjectsPostRequest:
    properties:
      projectName:
        type: string
        description: project name
      phpVersion:
        type: string
        description: php version is used in the project
