swagger: '2.0'
info:
  title: Shifter API
  description: Shifter API allows you to operate all Shifter resources, which are projects, archives, App, Generator.
  version: "1.0.0"
host: hz0wknz3a2.execute-api.us-east-1.amazonaws.com
schemes:
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: You can authorize Shifter using the accesstoken.
basePath: /production
produces:
  - application/json
paths:
  /projects:
    get:
      description: You can get the infomation of your projects
      tags:
        - projects
      security:
        - Bearer: []
      responses:
        200:
          description: the info of your projects
          schema:
            type: array
            items:
              "$ref": "#/definitions/ProjectsGetResponse"
    post:
      description: Create new project
      tags:
        - projects
      security:
        - Bearer: []
      parameters:
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/ProjectsPostRequest'
        - name: archive_id
          in: query
          required: true
          description: Specify an archive to create a project
          type: string
      responses:
        200:
          description: Success
  /projects/{site_id}:
    delete:
      description: Delete your project
      tags:
        - projects
      security:
        - Bearer: []
      parameters:
        - name: site_id
          in: path
          required: true
          description: project ID
          type: string
      responses:
        200:
          description: Success
  /containers/{site_id}:
    get:
      description: You can the status of App
      security:
        - Bearer: []
      tags:
        - containers
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
        - name: notification_id
          in: query
          required: true
          description: ID required to acquire App state
          type: string
      responses:
        200:
          description: the status of App
          schema:
            type: string
    post:
      description: Import archive to App
      security:
        - Bearer: []
      tags:
        - containers
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/ContainersPostRequest'
      responses:
        200:
          description: 成功
    put:
      description: Start App
      security:
        - Bearer: []
      tags:
        - containers
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
    delete:
      description: Stop App
      security:
        - Bearer: []
      tags:
        - containers
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
  /staticsites/{site_id}:
    get:
      description: You can get the process of generating
      security:
        - Bearer: []
      tags:
        - staticsites
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: the process of generating
          schema:
            $ref: '#/definitions/StaticsitesGetResponse'
    post:
      description: Start to generate the plblished site.
      security:
        - Bearer: []
      tags:
        - staticsites
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
    delete:
      description: Delete the published site
      security:
        - Bearer: []
      tags:
        - staticsites
      parameters:
        - name: site_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
definitions:
  ProjectsGetResponse:
    properties:
      site_id:
        type: string
        description: project ID
      site_name:
        type: string
        description: project name
      site_owner:
        type: string
        description: the owner of project
      update_time:
        type: string
        description: published date by Generator
      docker_url:
        type: string
        description: App Url
  ProjectsPostRequest:
    properties:
      projectName:
        type: string
        description: project name
      phpVersion:
        type: string
        description: php version is used in the project
  ContainersPostRequest:
    properties:
      archive_id:
        type: string
  StaticsitesGetResponse:
    properties:
      percent:
        type: integer
        description: Progress rate of genetating
      step:
        type: string
        description: Progress step  of genetating
      update_time:
        type: string
      owner:
        type: string
      message:
        type: string
      disk_usage:
        type: string
    
